### ISSUE TITLE
Official Cake Visual Studio Extension

### ISSUE THREAD

**Issue by gep13** [wk-j/visual-studio-cake#4]
We did not know about this extension that you created, and as a result, we have just published an official Visual Studio Extension for Cake:

https://visualstudiogallery.msdn.microsoft.com/57a658df-3577-440a-93e5-9f2734d80686

Is there anything in your extension that is not covered by the new Extension?

Apologies for not reaching out to you sooner about this.  We didn't know that you had created this.

**Comment by gep13** [comment]
@wk-j would you be interested in contributing to the official extension?

I am sure that @agc93 would welcome any help that you could offer, and any ideas that you might have.

**Comment by wk-j** [comment]
Hi @gep13 

I just installed an official extension and it's looking great.
Let me try, I like to contribute if I can.

**Comment by gep13** [comment]
@wk-j that is great news!

Be sure to reach out to @agc93 and myself if you have any questions.

Is there anything in your extension that isn't in the official extension?  If so, can we port it over to the official extension?  Do you think your extension should be unpublished in the Visual Studio Gallery?  Do you think this would avoid confusion?

Thanks!

**Comment by wk-j** [comment]
@gep13 

My vsix is very simple, I don't see any function can move.
Let's focus on official extension and I'm agree to unpublish my vsix in Visual Studio Gallery.

**Comment by gep13** [comment]
@wk-j that is great news, thank you.
